/* eslint-disable */
// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ImportOptions = ("EntityClass" | "FormDialog" | "Process" | "Repository" | "Enum")

export interface Database {
  creationError: CreationError[];
  databaseData: DatabaseData;
  databaseEditorDataContext: DatabaseEditorDataContext;
  databaseEditorDBContext: DatabaseEditorDBContext;
  databaseImportCreationArgs: DatabaseImportCreationArgs;
  databaseInfoData: DatabaseInfoData;
  [k: string]: unknown;
}
export interface CreationError {
  message: string;
  name: string;
  type: ImportOptions;
}
export interface DatabaseData {
  context: DatabaseEditorDataContext;
  databaseNames: string[];
}
export interface DatabaseEditorDataContext {
  app: string;
  file: string;
  pmv: string;
}
export interface DatabaseEditorDBContext {
  app: string;
  databaseName: string;
  file: string;
  pmv: string;
}
export interface DatabaseImportCreationArgs {
  context: DatabaseEditorDataContext;
  options: TableOptions[];
}
export interface TableOptions {
  database: string;
  namespace: string;
  table: DatabaseTable;
  type: ImportOptions;
}
export interface DatabaseTable {
  columns: DatabaseColumn[];
  entityClassName: string;
  name: string;
}
export interface DatabaseColumn {
  autoIncrement: boolean;
  entityAttributeName: string;
  entityAttributeType: string;
  generate: boolean;
  name: string;
  primaryKey: boolean;
  type: string;
}
export interface DatabaseInfoData {
  connectionName: string;
  tables: DatabaseTable[];
}
