/* eslint-disable */
// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ImportOptions = ("EntityClass" | "FormDialog" | "Process" | "Repository" | "Enum")

export interface Database {
  creationError: CreationError[];
  databaseConfigurations: DatabaseConfigurations;
  databaseData: DatabaseData;
  databaseEditorDataContext: DatabaseEditorDataContext;
  databaseEditorDBContext: DatabaseEditorDBContext;
  databaseEditorSaveArgs: DatabaseEditorSaveArgs;
  databaseEditorTableContext: DatabaseEditorTableContext;
  databaseImportCreationArgs: DatabaseImportCreationArgs;
  databaseTableData: DatabaseTableData;
  databaseTableInfoData: DatabaseTableInfoData;
  editorFileContent: EditorFileContent;
  jdbcDriverProperties: JdbcDriverProperties[];
  [k: string]: unknown;
}
export interface CreationError {
  message: string;
  name: string;
  type: ImportOptions;
}
export interface DatabaseConfigurations {
  connections: DatabaseConfigurationData[];
  helpUrl: string;
}
export interface DatabaseConfigurationData {
  additionalProperties: MapStringString;
  driver: string;
  icon: string;
  maxConnections: number;
  name: string;
  properties: MapStringString;
}
export interface MapStringString {
  [k: string]: string;
}
export interface DatabaseData {
  context: DatabaseEditorDataContext;
  databaseNames: MapStringListString;
}
export interface DatabaseEditorDataContext {
  app: string;
  file: string;
  pmv: string;
}
export interface MapStringListString {
  [k: string]: string[];
}
export interface DatabaseEditorDBContext {
  app: string;
  databaseName: string;
  file: string;
  pmv: string;
  tableNames: string[];
}
export interface DatabaseEditorSaveArgs {
  context: DatabaseEditorDataContext;
  data: DatabaseConfigurations;
  directSave: boolean;
}
export interface DatabaseEditorTableContext {
  app: string;
  databaseName: string;
  file: string;
  pmv: string;
}
export interface DatabaseImportCreationArgs {
  context: DatabaseEditorDataContext;
  options: TableOptions[];
}
export interface TableOptions {
  database: string;
  namespace: string;
  table: DatabaseTable;
  type: ImportOptions;
}
export interface DatabaseTable {
  columns: DatabaseColumn[];
  entityClassName: string;
  name: string;
}
export interface DatabaseColumn {
  autoIncrement: boolean;
  entityAttributeName: string;
  entityAttributeType: string;
  generate: boolean;
  name: string;
  primaryKey: boolean;
  type: string;
}
export interface DatabaseTableData {
  connectionName: string;
  tables: string[];
}
export interface DatabaseTableInfoData {
  connectionName: string;
  tables: DatabaseTable[];
}
export interface EditorFileContent {
  content: string;
}
export interface JdbcDriverProperties {
  databaseProduct: string;
  name: string;
  properties: MapStringString;
}
