# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  microsoft:
    connector:
      # Your Azure Application (client) ID
      appId: MyAppId
      # Secret key from your applications "certificates & secrets"
      #[password]
      secretKey: ${decrypt:S2z4BHUX2LDnX7E7KsDxIg==}
